### ISSUE TITLE
Mysqli adapter overwrites previous statement iterators with each new query

### ISSUE THREAD

**Issue by AlexHowansky** [zendframework/zf1#127]
Creating a new query wipes out all previously defined statement handles, making it impossible to fetch further rows from them. For example, this works fine:

    $db = Zend_Db::factory('Mysqli', array(...));
    $stmt1 = $db->query('select * from foo');
    while ($row1 = $stmt1->fetch()) { ... }

However, this gives no results because the first fetch() fails:

    $stmt1 = $db->query('select * from foo');
    $stmt2 = $db->query('select * from bar');
    while ($row1 = $stmt1->fetch()) { ... }

It appears that each previous driver statement gets wiped every time a new query is made:

    $stmt1 = $db->query('select * from foo');
    var_dump($stmt1->getDriverStatement());
    $stmt2 = $db->query('select * from bar');
    var_dump($stmt1->getDriverStatement());

Outputs:

    class mysqli_stmt#6 (10) { ... }
    NULL

I.e., calling query() again wipes out the statement iterator for all previous queries. If I try to do nested queries, I'll only get one iteration of the outside loop because the iterator will get destroyed during the first iteration:

    $stmt1 = $db->query('select * from foo');
    while ($row1 = $stmt1->fetch()) {
        $stmt2 = $db->query('select * from bar');
        while ($row2 = $stmt2->fetch()) { .... }
    }

Simply changing the driver from Mysqli to Pdo_Mysql resolves this issue:

    $db = Zend_Db::factory('Pdo_Mysql', array(...));
    $stmt1 = $db->query('select * from foo');
    var_dump($stmt1->getDriverStatement());
    $stmt2 = $db->query('select * from bar');
    var_dump($stmt1->getDriverStatement());

Outputs:

    class PDOStatement#6 (1) { ... }
    class PDOStatement#6 (1) { ... }

**Comment by ezimuel** [comment]
I'm closing this because no unit test and possible fix provided since 2014.
