### ISSUE TITLE
Date validation doesn't work

### ISSUE THREAD

**Issue by jacobweber** [zendframework/zf1#207]
I'm trying to use Zend_Validate_Date, based on the instructions [here](http://framework.zend.com/manual/1.12/en/zend.validate.set.html#zend.validate.set.date.basic).

First, the instructions don't say anything about how the formats should be specified.

But even following the given example, isValid returns true for values that are obviously incorrect:

```php
$validator = new Zend_Validate_Date(array('format' => 'yyyy'));
echo $validator->isValid('1'); // prints "1"
echo $validator->isValid('123123123'); // prints "1"
```

If I'm correct in guessing that the formats are the CLDR formats mentioned [here](http://framework.zend.com/manual/1.12/en/zend.date.constants.html#zend.date.constants.phpformats), then it doesn't work with months and days either:
```php
$validator = new Zend_Validate_Date(array('format' => 'M/d/yyyy'));
echo $validator->isValid('123123123'); // prints "1"
```

**Comment by froschdesign** [comment]
At this point we can not change the current behaviour or change the parsing/extraction of the date parts.
Please use PHP's `DateTime` class or the new validators from ZF2.

I will close this issue.
