### ISSUE TITLE
Upgrade Zend_Service_DeveloperGarden to developergarden api 5.1.1

### ISSUE THREAD

**Issue by nrunde** [zendframework/zf1#250]
Service isn't longer available from integrated api version 4 (since 30th Nov.). An upgrade to the newest api version is needed for existing applications.

https://www.developergarden.com/apis/documentation/bundle/telekom-api-rest/Manual.pdf

**Comment by froschdesign** [comment]
@mhujer 
Any updates?

**Comment by mhujer** [comment]
Ping @tomhoefer ?

**Comment by froschdesign** [comment]
> Developer Garden says 'Good Bye'

https://www.developergarden.com/goodbye/

**Comment by akrabat** [comment]
I think we can safely close this one then! 

Should we remove Zend_Service_DeveloperGarden completely? 

(ping @weierophinney)

**Comment by mhujer** [comment]
Can I prepare a PR? I like removing of code :-)

**Comment by akrabat** [comment]
@mhujer: Yes! :)
