### ISSUE TITLE
Zend_Service_Amazon_S3: Can't debug

### ISSUE THREAD

**Issue by diogoca** [zendframework/zf1#288]
I'm using ZF 1.12.3 and putObject method stopped works from localhost (Eg: 192.168.0.1 or fakeDomain.tld), always returns bool(false), no error, notice or warning.

In online production server works fine. After hours, i captured error by Wireshark and discovery the error, its about "RequestTimeTooSkewed ". Is it possible display exception when putObject or other methods return false. Believe to be most useful to debug. 

Thank you.

**Comment by froschdesign** [comment]
This is a good idea, but at this point we can not change the API (current behaviour or return type).

So I will close this issue.
