### ISSUE TITLE
Zend_Http_Header_SetCookie and multiple cookies with setHeadersRaw()

### ISSUE THREAD

**Issue by kdeubert** [zendframework/zf1#295]
Tested in Version 1.12.1, checked the 1.12.3 code and is still unchanged.

The way Zend_Http_Header_SetCookie works with the suggested usage of Zend_Controller_Response_Abstract->setRawHeader() fails if repeated with multiple cookies to set.
Only the last cookie will get set in the response.

The reason: In Zend_Controller_Response_Abstract->sendHeaders() the $replace parameter for the header() call will never be set to false for all raw headers, the consequence is it will replace itself for every Set-Cookie raw header.

Also see this stackoverflow thread and my answer there:
http://stackoverflow.com/questions/5961223/how-to-use-cookies-in-zend

It also contains the zf docs 1.12 link but it seems to be down right now:
http://framework.zend.com/manual/1.12/en/zend.controller.response.html#zend.controller.response.headers.setcookie

My workaround right now is to use

```
$this->getResponse()->setHeader('Set-Cookie', $cookie->getFieldValue(), false); 
```

instead of

```
$this->getResponse()->setRawHeader($cookie);
```

**Comment by Nebojsaa** [comment]
All right, so it works for two cookies. But what happens if I have to set 4 of them ? 
How can I do that ? 

            $cookieStreetNumber = new Zend_Http_Header_SetCookie('user_street_number', $cookieStreetNumber, NULL ,'/');
            $cookieGender = new Zend_Http_Header_SetCookie('user_gender', $cookieGender, NULL ,'/');
            $cookieBirthdate = new Zend_Http_Header_SetCookie('user_birthdate', $cookieBirthdate, NULL ,'/');
            $cookiePostalCode = new Zend_Http_Header_SetCookie('user_postalcode', $cookiePostalCode, NULL ,'/');
            $headerLine = $cookieStreetNumber->toStringMultipleHeaders($cookieGender, $cookiePostalCode, $cookieBirthdate);
            $this->getResponse()->setRawHeader($headerLine);

**Comment by froschdesign** [comment]
> ```php
$headerLine = $cookieStreetNumber->toStringMultipleHeaders($cookieGender, $cookiePostalCode, $cookieBirthdate);
```

Wrong parameter(s): https://github.com/zendframework/zf1/blob/master/library/Zend/Http/Header/SetCookie.php#L538

(Btw. This is not a support forum!)
