### ISSUE TITLE
Zend_Controller_Dispatcher_Abstract::_formatName() inconsistent with Action name handling

### ISSUE THREAD

**Issue by divinoro** [zendframework/zf1#440]
In normal case, URL is splited to [:module]/[controller]/[action], eg

domain.com/controller/action

In case of using unallowed chars, like "!" or "@", these are removed, so URL like

domain.com/!controller/action

is cleaned and used as 

domain.com/controller/action

However, names of view folder is not claned, so entering

domain.com/!controller

will reult in calling "controller" controller and index action, trying to access

views/scripts/!controller/index.phtml

resulting in error 500, instead of 404 not found

Expecting behavior:

Approach should be consistent, so either keep exclamation mark in both (controller and controller folder) of remove unallowed chars also from view folder.

Why it's problem: some pages using #! to address dynamic pages using ajax calls, but crawlerrs are ignoring # and thats resulting in exceptions. 

Thank you.
Ivan

**Comment by froschdesign** [comment]
@akrabat 
Do you have an idea?

Maybe this one:
```php
$controller = substr(
    $dispatcher->formatControllerName($request->getControllerName()),
    0,
    -10
);
```
https://github.com/zendframework/zf1/blob/master/library/Zend/Controller/Action/Helper/ViewRenderer.php#L845

**Comment by akrabat** [comment]
That looks sane to me.

**Comment by secu-ring** [comment]
There is a problem with the changed code part when the controller name don't have the word "Controller" as suffix. As I remember in ZF1 the controller names should be "Modulename_ControllerName" without the word "Controller". When I change a controller namer from maybe "Index_Index" to "IndexController" or even "Index_IndexController" the autoloader will not find the class.

The problem doesn't occur in version 1.12.9. When I change the code to the following, it works again.

```php
$controller = $dispatcher->formatControllerName($request->getControllerName());
        
if (false !== strpos('controller', strtolower($controller))) {
    $controller = substr($controller, 0,-10);
}
```

Would be nice when You could fix this Problem.

Regards

**Comment by froschdesign** [comment]
@secu-ring 
Do you have overwritten the dispatcher? The standard dispatcher [adds](https://github.com/zendframework/zf1/blob/master/library/Zend/Controller/Dispatcher/Abstract.php#L105) always the string "Controller".

**Comment by secu-ring** [comment]
@froschdesign 
Yes, we're doing this. Than it makes sense that it won't work - we have to extend the View Renderer also to override these method.

Thanks for your hint.

**Comment by froschdesign** [comment]
@secu-ring 
I will add a condition.

**Comment by froschdesign** [comment]
@secu-ring 
See 988d293f0d3128018d461cc22fcf2e7bcb6ffdd7

**Comment by weierophinney** [comment]
@secu-ring Can you post a note here indicating whether or not the patch from @froschdesign fixes the issue for you?

(Re-opening, as the issue was not resolved to satisfaction previously based on reports.)

**Comment by secu-ring** [comment]
@weierophinney Yes the patch solved our problem.

**Comment by mirow** [comment]
This seems to break compatibility with CamelCase controller names?

I have a controller class named "MetadataValidationController", and the view files are in a folder called "metadata-validation".  This worked fine before, but resently it stopped working as Zend now looks for the view files in "metadavalidation" folder.

**Comment by froschdesign** [comment]
> I have a controller class named "MetadataValidationController", and the view files are in a folder called "metadata-validation".

These behaviour was never included in any unit tests – really shitty!

> This worked fine before, but resently it stopped working as Zend now looks for the view files in "metadavalidation" folder.

Right, because the only word delimiters are "-" and ".".

**Comment by ianlayton** [comment]
@froschdesign I can't tell from you comment...is this something that will be 'fixed' to go back to the way it has worked in the past or is this something we will need to account for and adjust as a developer?

**Comment by froschdesign** [comment]
@mirow  and @ianlayton 
See: #537

**Comment by akrabat** [comment]
Should we roll a new release fairly quickly for this, @froschdesign ?

**Comment by froschdesign** [comment]
@akrabat 
Sure, but I see one more problem: #534
This should be fixed before we roll out the next release.

**Comment by bbrala** [comment]
Fun stuff, this does change how paths to views are resolved, and breaks current sites since it cannot find the views. Sure its a fix, but the merge breaks like, every site we built. Painfull "fix".

**Comment by akrabat** [comment]
@bbrala Can you provide an example of what's broken for you?

**Comment by bbrala** [comment]
Ok, I've looked into this a little, and things started to fall apart in januari, before the code just user $request->getControllerName(); and that was it. I've put the old and new values in a list to show what is happening.


        echo '<br>Old name (pre 40dd702): ' . $request->getControllerName();;

        // Format controller name
        require_once 'Zend/Filter/Word/CamelCaseToDash.php';
        $filter     = new Zend_Filter_Word_CamelCaseToDash();
        $controller = $filter->filter($request->getControllerName());
        echo '<br>After CamelcaseFilter: ' . $controller;
        $controller = $dispatcher->formatControllerName($controller);
        echo '<br>After dispatcherformat: ' . $controller;
        if ('Controller' == substr($controller, -10)) {
            $controller = substr($controller, 0, -10);
        }
        echo '<br>new name: ' . $controller . ' <hr>';

Old name (pre 40dd702): Mainnav
After CamelcaseFilter: Mainnav
After dispatcherformat: MainnavController
new name: Mainnav

Old name (pre 40dd702): tekst
After CamelcaseFilter: tekst
After dispatcherformat: TekstController
new name: Tekst

Old name (pre 40dd702): head-html
After CamelcaseFilter: head-html
After dispatcherformat: HeadHtmlController
new name: HeadHtml 

Hope that helps

**Comment by froschdesign** [comment]
@bbrala 
> I've put the old and new values in a list to show what is happening.

Sorry, but where is the problem?

```php
/**
 * @group GH-440
 * @dataProvider providerControllerNames
 */
public function testControllerNames($controllerName, $viewScriptDir)
{
   $this->request->setControllerName($controllerName)
                 ->setActionName('index');

   $this->helper->setActionController(
       new Bar_IndexController(
           $this->request, $this->response, array()
       )
   );

   $this->assertEquals(
       sprintf('%s/index.phtml', $viewScriptDir),
       $this->helper->getViewScript()
   );
}

/**
 * Data provider for testControllerNames
 * @group GH-440
 * @return array
 */
public function providerControllerNames()
{
    return array(
        array('Mainnav', 'mainnav'),
        array('tekst', 'tekst'),
        array('head-html', 'head-html'), // strange controller name!
    );
}
```
**Tests passed**

Did I miss something?

**Comment by bbrala** [comment]
That is pretty weird. I'll double check this and see if i can expand a bit on my case. Maybe i echo the result to early

**Comment by bbrala** [comment]
Ok, i cannot reproduce the problem why this was changed, i will check with the developer who fixed the issue (or was it xD) and see where it broke. It seems to have something to do with something like InschrijvenStap1 first translating into inschrijven-stap1 and now to inschrijven-stap-1. I don't have the today to check it more, but i'll try to make a proper demonstration later.
