### ISSUE TITLE
Zend_Dojo_View_Helper_Dojo_Container setCdnVersion error...

### ISSUE THREAD

**Issue by acajaja** [zendframework/zf1#488]
see line 430 of Zend_Dojo_View_Helper_Dojo_Container; the setCdnVersion method.

The regular expression '/^[1-9]\\.\[0-9\](\\.[0-9])?$/' used to match the Dojo CDN version fails to recognize a two (or more) dijit minor version number. This prevents developers from using the newest versions of Dojo 1.10.x.

Proposed solution:

'/^[1-9]\\.\[0-9\]{1,2}(\\.[0-9])?$/'

**Comment by froschdesign** [comment]
@acajaja 
Thanks for reporting!
