### ISSUE TITLE
Implement USE INDEX/FORCE INDEX for MySQL

### ISSUE THREAD

**Issue by tsmgeek** [zendframework/zf1#489]
There was a ZF1 ticket http://framework.zend.com/issues/browse/ZF-7570 that was a request to implement USE INDEX/FORCE INDEX in the Zend_Db_Select class.

It seems that this user implemented it directly within the main Zend_Db_Select class without any abstraction to the Adapters, would this have been incorrect?

If it was re-factored into such and CLA provided could it be implemented?

**Comment by froschdesign** [comment]
Closing due inactivity.

Please feel free to send a PR.
