### ISSUE TITLE
Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed'

### ISSUE THREAD

**Issue by back-2-95** [zendframework/zf1#496]
Hello,

I get this error from Zend Server 8.0.1 with Z-Ray.
It has PHP 5.5.20.

Shouldn't ZF1 work with it?

Bactrace with all functions pointing to Zend Framework 1 classes and methods:
```
Backtrace [select all]
throw() at /home/_applications/myapp/vendor/zendframework/zendframework1/library/Zend/Stdlib/PriorityQueue.php: 187
serialize() at /home/_applications/myapp/vendor/zendframework/zendframework1/library/Zend/Stdlib/PriorityQueue.php: 187
serialize() at /home/_applications/myapp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php: 105
dispatch() at /home/_applications/myapp/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php: 105
run() at /home/_applications/myapp/vendor/zendframework/zendframework1/library/Zend/Application.php: 382
run() at /home/_applications/df-lms-lite/public/index.php: 83
```
I also posted this to Zend Server forum:
http://forums.zend.com/viewtopic.php?f=8&t=123183

**Comment by Ocramius** [comment]
Seems normal to me: you can't serialize a native closure.

What did you push to your `PriorityQueue`?

**Comment by back-2-95** [comment]
Nothing. That's the weird thing. Is there some class inside Zend using that PriorityQueue?

**Comment by back-2-95** [comment]
I searched quickly this repo (https://github.com/zendframework/zf1/search?utf8=%E2%9C%93&q=PriorityQueue) and Lucene + EventManager uses PriorityQueue.

I use EventManager in my application.

**Comment by back-2-95** [comment]
I have this kind of events in my module bootstraps and if I remove them all, the error disappers.

<?php

class Mymodule_Bootstrap extends Zend_Application_Module_Bootstrap
{
	public function _initEvents()
	{
		$events = $this->getApplication()->events();

		$events->attach("some.event",  function($e) {
			// Do something
		});
	}
}

And in that events() call I make
$this->events = new Zend_EventManager_EventManager('identifier');

And that class includes PriorityQueue class.

Should I make my events another way or is this something which conflicts between PHP 5.5 and Zend Framework 1 EventManager/PriorityQueue ?

**Comment by back-2-95** [comment]
Appently that was the reason, I commented all event attchment with anoymous functions.
Then I converted some to this form and it worked:

$events->attach('some.event, [$this, 'onSomeEvent']);

But shouldn't the original form work? As it is the only way describes in the manual:
http://framework.zend.com/manual/1.12/en/zend.event-manager.event-manager.html

**Comment by back-2-95** [comment]
Update: this seems to be problem with Zend Framework 1 Z-ray plugin. So if you remove/disable it, your code will work. I guess they're fixing in the following versions but for me removing the plugin was enough.
