### ISSUE TITLE
Cannot parse huge documents in Zend_Dom_Query

### ISSUE THREAD

**Issue by croensch** [zendframework/zf1#504]
In ``Zend_Dom_Query::queryXpath()`` the document is only a string and the HTML/XML loading is hard coded so that passing an option like
```$domDoc->loadHTML($document, LIBXML_PARSEHUGE);```
is impossible.

The result is that the found nodes may be truncated.

If we could inject a DOMDocument object instead, right into ``Zend_Dom_Query::setDocument()``, the loading of the Document could happen outside of the existing code.

**Comment by froschdesign** [comment]
@croensch 
Create a PR and I will review it.

**Comment by froschdesign** [comment]
ping @croensch
