### ISSUE TITLE
View renderer controller name fix breaks use of custom dispatcher

### ISSUE THREAD

**Issue by akrabat** [zendframework/zf1#506]
See https://github.com/zendframework/zf1/issues/440#issuecomment-70542632

**Comment by akrabat** [comment]
Fixed in 988d293f0d3128018d461cc22fcf2e7bcb6ffdd7

**Comment by froschdesign** [comment]
@akrabat 
:+1:

**Comment by akrabat** [comment]
We're already to go for a 1.12.11 release - when @weierophinney gets time :)
