### ISSUE TITLE
!IE conditional comments bug

### ISSUE THREAD

**Issue by jackplug** [zendframework/zf1#515]
Ref: https://github.com/zendframework/zf1/blob/master/library/Zend/View/Helper/HeadScript.php#L458
This works correctly in the case of downlevel-hidden conditional comments, but for downlevel-revealed conditional comments (which are needed for !IE), the rendered HTML is wrong.

Current rendered output:
````
<!--[if !IE]> <script>
...
</script><![endif]-->
```` 
Correctly rendered output:
````
<![if !IE]> <script>
...
</script><![endif]-->
```` 
If the '--' characters are not removed, every browser treats this as a comment.
More info: https://msdn.microsoft.com/en-us/library/ms537512%28v=vs.85%29.aspx

/cc @tomasfejfar @mhujer

**Comment by froschdesign** [comment]
> ```html
<![if !IE]> <script>
...
</script><![endif]-->

This is invalid code. Better:

```html
<!--[if expression]><!-->
  HTML
<!--<![endif]-->
```
http://css-tricks.com/downlevel-hidden-downlevel-revealed/

**Comment by jackplug** [comment]
I'm glad that you pointed that out :) Valid code is much, **much**, better. 

So, we need to add ``<!-->`` after the expression, then we keep the code clean. 

I updated a quick JSFiddle to demonstrate http://jsfiddle.net/jackplug/opsftwLf/2/ your suggestion (anyone want to test this in IE8, you should use the fullscreen url https://jsfiddle.net/jackplug/opsftwLf/2/embedded/result/)

**Comment by jackplug** [comment]
@froschdesign :thumbsup:

**Comment by tomasfejfar** [comment]
:+1:
