### ISSUE TITLE
Zend_Locale does not honor parentLocale configuration

### ISSUE THREAD

**Issue by barbazul** [zendframework/zf1#516]
This has become obvious after the update to CLDR 25 in which currency symbol position changed for es.xml but not for es_419.xml

All Latin American locales should inherit from es_419.xml as specified in supplementalData.xml line 409

```xml
<parentLocale parent="es_419" locales="es_AR es_BO es_CL es_CO es_CR es_CU es_DO es_EC es_GT es_HN es_MX es_NI es_PA es_PE es_PR es_PY es_SV es_US es_UY es_VE"/>
```

Try the following script:

```php
$locale = new Zend_Locale('es_AR');
$curr = new Zend_Currency(null, $locale);
echo $curr->toCurrency(10);
```

Expected result ```$10```

Actual result ```10 $```

**Comment by barbazul** [comment]
For completion, here's the ticket I opened about this issue in CLDR http://unicode.org/cldr/trac/ticket/8194

**Comment by froschdesign** [comment]
"parentLocales" is not supported in the current implementation of `Zend_Locale`.

(Note to me: Another reason to mark `Zend_Locale` as deprecated.)

**Comment by froschdesign** [comment]
Workaround:

```php
$fmt = new NumberFormatter('es_AR', NumberFormatter::CURRENCY);
echo $fmt->formatCurrency(10, 'ARS');
```
Output:
```
$10,00
```

**Comment by barbazul** [comment]
Unfortunately, this workaround is not good for me as I am working in  the
Magento e-commerce application and to apply this patch I would need to
modify (or override) core libraries that would render the aplication
unupgradeable.

The best fix in this scenario was to simply modify the XML files.

Proper support would be preferrable I suppose, but this simple fix worked
for me without issues so I stopped complaining.

**Comment by froschdesign** [comment]
> I am working in  the Magento e-commerce

Good to know.

> The best fix in this scenario was to simply modify the XML files.

Bad idea, because all XML files come from an external library ([CLDR](http://cldr.unicode.org/)) and we can not change this library.

**Comment by barbazul** [comment]
Yes, I am aware. That is the reason why propper support would be
preferrable.

However, simply changing the symbol position in  the XML files was the fix
with the lowest impact in the application and the one that was the easiest
to track in case of an upgrade.

**Comment by barbazul** [comment]
Thank you for your fix. I tried it in a Magento application and it works perfectly
