### ISSUE TITLE
igbinary support in Zend_Cache

### ISSUE THREAD

**Issue by deltamualpha** [zendframework/zf1#522]
Is there any interest in supporting non-default serialization methods within Zend_Cache? I'm thinking specifically `igbinary` over the default.

**Comment by froschdesign** [comment]
> Is there any interest in supporting non-default serialization methods within Zend_Cache? 

The [ZF2](https://github.com/zendframework/zf2) is a better place for this suggestion. Thanks!

**Comment by axot** [comment]
We want use `igBinary` in ZF1 for performance reason. It seems we have to modify `Zend_Cache_Core` for this. By default before saving data to APC, `Zend_Cache_Core` will `serialize` all data to `string` type, which causes `igBinary` not working for. So I disabled `serialize/unserialize` line in `Zend_Cache_Core`. Is there any side effect with this code? Thank you

```php
public function save($data, $id = null, $tags = array(), $specificLifetime = false, $priority = 8)
{
    if ($this->_options['automatic_serialization']) {
        // disabled serialize for using igBinary
        // $data = serialize($data);
    } else {
        if (!is_string($data)) {
            //Zend_Cache::throwException("Datas must be string or set automatic_serialization = true");
        }
    }
 }

public function load($id, $doNotTestCacheValidity = false, $doNotUnserialize = false)
{
    if ((!$doNotUnserialize) && $this->_options['automatic_serialization']) {
        // we need to unserialize before sending the result
        // disabled serialize for using igBinary
        return $data;
    }
    return $data;
}
```
