### ISSUE TITLE
DB connection issue when trying to connect with Zend Framework Abstract.php No Such File Or Directory

### ISSUE THREAD

**Issue by crmpicco** [zendframework/zf1#524]
I am trying to setup a ZF1 application on my local machine using MAMP. I am attempting to run the Ruckusing Database migrations, however it appears that ZF1 cannot connect to my DB.

This is the command I am running and the error I get.

```
crmpicco-MacBook:confirmation crmpicco$ php vendor/ruckusing/ruckusing-migrations/ruckus.php db:migrate ENV=development

Array
(
    [directory] => webapp
    [type] => mysql
    [host] => localhost
    [port] => 3306
    [database] => crmpicco_confirmation
    [user] => root
    [password] => root
    [socket] => /Applications/MAMP/tmp/mysql/mysql.sock
    [charset] => utf8
)

Abstract.php(144) : SQLSTATE[HY000] [2002] No such file or directory
```

Where should I look to resolve this issue?

phpinfo reads as follows:

PDO 
PDO support enabled 

PDO drivers 
sqlite, pgsql, mysql pdo_mysql 

PDO Driver for MySQL enabled 
Client API version 5.5.38 
Directive Local Value Master Value 
pdo_mysql.default_socket /Applications/MAMP/tmp/mysql/mysql.sock /Applications/MAMP/tmp/mysql/mysql.sock

**Comment by mhujer** [comment]
It looks more like a Ruckusing issue than the ZF1 one

**Comment by crmpicco** [comment]
@mhujer I'll maybe enquire in that project, however everything i've came across online points to ZF code - https://www.google.co.uk/search?q=Abstract.php%28144%29+:+SQLSTATE[HY000]+[2002]+No+such+file+or+directory&ie=utf-8&oe=utf-8&gws_rd=cr&ei=XnX9VJHMD8uHPdC4gYgH

**Comment by froschdesign** [comment]
> ```php
[port] => 3306
```

[The standard port for MySQL on MAMP is 8889.](http://www.mamp.info/en/documentation/#q6)

**Comment by froschdesign** [comment]
ping @crmpicco

**Comment by froschdesign** [comment]
@crmpicco 
If this still an issue please give us some feedback.
