### ISSUE TITLE
Failing unit test: Zend_Validate_EmailAddressTest::testIdnHostnameInEmaillAddress

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf1#534]
See:

- https://travis-ci.org/zendframework/zf1/jobs/55759029#L1354
- https://github.com/zendframework/zf1/blob/master/tests/Zend/Validate/EmailAddressTest.php#L629

**Comment by froschdesign** [comment]
ping @mhujer

**Comment by mhujer** [comment]
Strange :-( I will have a look

**Comment by akrabat** [comment]
This is failing because we do an MX-record lookup (using [getmxr](http://php.net/manual/en/function.getmxrr.php)) to detrèsbonsdomaines.com which no longer has an MX record.

**Comment by mhujer** [comment]
I hope that zürich.ch won't stop using MX records for their domain :-)

**Comment by akrabat** [comment]
Yeah - we need a better solution really!  However, I'm hoping that they won't stop in the near future!
