### ISSUE TITLE
Build job for PHP 5.2 on Travis CI is broken

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf1#543]
See: https://travis-ci.org/zendframework/zf1/jobs/56745260 (Example)

**Comment by froschdesign** [comment]
@mhujer 
Can you look at this? Thanks!

**Comment by akrabat** [comment]
I'd like this fixed, but I don't think it should stop the release of 1.12.12. 

Unless anyone has anything pressing, I'll ask Matthew to release when he can (which is likely to be end of next week-ish)

**Comment by mhujer** [comment]
I will try to have a look over the weekend
