### ISSUE TITLE
Session Validators throw 'general' Session Exception during Session start

### ISSUE THREAD

**Issue by holtkamp** [zendframework/zf1#547]
Session Validators (like Zend_Session_Validator_HttpUserAgent), provide an easy and extendable mechanism to validate sessions during startup.

However, when validation fails during session startup, a general Zend_Session_Exception is thrown. The same Zend_Session_Exception can be thrown due to other causes, for example:

- [the session is started implicitly using a Zend_Session_Namespace](https://github.com/zendframework/zf1/blob/release-1.12.11/library/Zend/Session.php#L449)
- [output has already been sent to the browser when starting the session](https://github.com/zendframework/zf1/blob/release-1.12.11/library/Zend/Session.php#L456)
- [the session has been auto started](https://github.com/zendframework/zf1/blob/release-1.12.11/library/Zend/Session.php#L464)

How can one be sure that an Exception caught during session start was caused by a certain Validator that fails? Would it not be better to have:

- either a general Exception class used by all Validators: Zend_Session_Validator_Exception, this would be better than nothing, but when using multiple Exceptions this also might become to 'general'
- or a per-validator specific Exception, for example: Zend_Session_Validator_HttpUserAgent_Exception

Maybe I am missing something, but in case one of the aforementioned solutions is regarded viable, I can come up with a PR, starting with the first suggestion which seems quite straight forward.

**Comment by froschdesign** [comment]
Fixed with #548
