### ISSUE TITLE
Notice "Undefined index: browser_version"

### ISSUE THREAD

**Issue by marcing** [zendframework/zf1#550]
Zend_Http_UserAgent_AbstractDevice, line 512

For User Agent value of "Mozilla"

Cheers

**Comment by froschdesign** [comment]
@marcing 
Can you provide the user agent or an unit test?

**Comment by marcing** [comment]
I did provide it. It is "Mozilla".

**Comment by froschdesign** [comment]
Ah, okay. Thanks!

**Comment by marcing** [comment]
Thank you too. I am happy it will be finally fixed!

**Comment by froschdesign** [comment]
@marcing 
Thanks for reporting! :+1:
