### ISSUE TITLE
Recaptcha v2 form element

### ISSUE THREAD

**Issue by xorock** [zendframework/zf1#554]
Do you have plans to update the forms so that they can handle recaptcha v2 natively?

**Comment by froschdesign** [comment]
Please check the Contributor Guide:

 > Zend Framework version 1 is currently supported in maintenance mode where bug fixes are accepted until End Of Life is announced. Version 1.12 is the last version in the 1.x series. If it is a new feature you wish to contribute, the best place to take this is ZF2.

http://framework.zend.com/participate/contributor-guide-v1

**Comment by xorock** [comment]
I've created repository including ReCaptcha v2 service, form decorators and others. Feel free to download and contribute.

https://github.com/xorock/ZF1-Google-Recaptcha-v2
