### ISSUE TITLE
doc: Zend Framework Dependencies table unreadable

### ISSUE THREAD

**Issue by glensc** [zendframework/zf1#557]
the table is corrupted:
                http://framework.zend.com/manual/1.12/en/requirements.introduction.html#requirements.dependencies
something between Zend_Auth and Zend_Captch is messed up

![screenshot-1](https://cloud.githubusercontent.com/assets/199095/7392459/95384276-ee90-11e4-8134-7a9338486621.png)

**Comment by froschdesign** [comment]
@glensc 
Thanks for reporting!

**Comment by glensc** [comment]
any ideas when the website gets updated (how it's updated anyway?)

**Comment by froschdesign** [comment]
> any ideas when the website gets updated

With the next release.

**Comment by akrabat** [comment]
Our current plans are for the next release to be next week.
