### ISSUE TITLE
Zend Cache Backend for MongoDb

### ISSUE THREAD

**Issue by holtkamp** [zendframework/zf1#563]
Not sure whether this is an 'issue', but more a question. 

Is new functionality still considered for Zend Framework 1?

Would this Cache Backend be a candidate to be adopted in the library?
https://github.com/AntonStoeckl/Zend_Cache_Backend_Mongo

Both @AntonStoeckl and I don't really have a lot of time to maintain it, and it has been used in production for over a year without problems. I am now considering putting it on Packagist, but adopting it in Zend Framework itself would be more appropriate...

**Comment by froschdesign** [comment]
1. Look at the Contributor Guide:
  
 > Zend Framework version 1 is currently supported in maintenance mode where bug fixes are accepted until End Of Life is announced. Version 1.12 is the last version in the 1.x series. If it is a new feature you wish to contribute, the best place to take this is ZF2.

  http://framework.zend.com/participate/contributor-guide-v1
2. ZF2 has already a [MongoDb adapter](http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html#the-mongodb-adapter)
3. ZF3 is on the way

**Comment by holtkamp** [comment]
MM, ok, thanks for the response, will register it at Packagist then for interested parties. Closing issue.

**Comment by froschdesign** [comment]
> will register it at Packagist then for interested parties

Good idea! :+1:

**Comment by froschdesign** [comment]
A suggestion: Rename your class, because `Zend_` is the wrong prefix.

**Comment by holtkamp** [comment]
mmm, why would ```Zend_``` be the wrong prefix? It IS Zend Framework 1 specific code right? Only it will not be adopted anymore...

**Comment by froschdesign** [comment]
> It IS Zend Framework 1 specific code right?

But this is not an official ZF class. (…and it will create confusion within composer.)

**Comment by froschdesign** [comment]
Btw. Unit tests are missing!

**Comment by holtkamp** [comment]
Yeah, that is where the lack of time comes in, combined with projects that have already been delivered. Thanks for the feedback, will try to come up with an appropriate solution!
