### ISSUE TITLE
Zend_Http_Exception "Invalid header value detected" on POST with Zend_Http_Client

### ISSUE THREAD

**Issue by pulseit-dennis** [zendframework/zf1#569]
In Zend Framework 1.12.12 I have found an issue when POSTing with a body using `Zend_Http_Client`.
I always receive a `Zend_Http_Exception` with the Message

> Invalid header value detected

It is thrown in the `_validateHeaderValue` method because of the value of the `Content-Length` header being neither a string, nor an object nor having a method `__toString()`. The `Content-Length` is also set by the `Zend_Http_Client` in method `_prepareBody`

```
        // Set the Content-Length if we have a body or if request is POST/PUT
        if ($body || $this->method == self::POST || $this->method == self::PUT) {
            $this->setHeaders(self::CONTENT_LENGTH, strlen($body));
        }
```

`strlen($body)` of course delivers an integer, so the Exception will be thrown

**Comment by froschdesign** [comment]
Already done: #567

Please look also at the closed tickets: #568 and #566
