### ISSUE TITLE
Incorrect application of timeout option in curl http client adapter

### ISSUE THREAD

**Issue by tasso85** [zendframework/zf1#582]
Hi,

after upgrade to the latest version of ZF1, I noticed that the `connect()` code for `Zend_Http_Client_Adapter_Curl` partially changed, from

    [...]
    // Set timeout
    curl_setopt($this->_curl, CURLOPT_CONNECTTIMEOUT, $this->_config['timeout']);
    [...]

to

    [...]
    if (defined('CURLOPT_CONNECTTIMEOUT_MS')) {
        curl_setopt($this->_curl, CURLOPT_CONNECTTIMEOUT_MS, $this->_config['timeout'] * 1000);
    } else {
        curl_setopt($this->_curl, CURLOPT_CONNECTTIMEOUT, $this->_config['timeout']);
    }
    
    if (defined('CURLOPT_TIMEOUT_MS')) {
        curl_setopt($this->_curl, CURLOPT_TIMEOUT_MS, $this->_config['timeout'] * 1000);
    } else {
        curl_setopt($this->_curl, CURLOPT_TIMEOUT, $this->_config['timeout']);
    }
    [...]

However, the second version seems to incorrectly apply the timeout parameter, which the docs states is the **connection** timeout, also as a general timeout.

This broke a part of our application, which relied on it to behave as stated in the docs, and now behaviour has changed.

I would therefore like to propose to split such option to `timeout` and `connecttimeout`, or something like that, to keep the behaviour separate, and also I think that the option should be set only where different from `NULL`.

**Comment by froschdesign** [comment]
See also: #402

**Comment by tasso85** [comment]
@froschdesign didn't see that, sorry for the duplicate report

**Comment by froschdesign** [comment]
> sorry for the duplicate report

Is this a duplicate? No!
The changes from #402 introduced the current behaviour in `Zend_Http_Client_Adapter_Curl`.

**Comment by akrabat** [comment]
I'm confused as to what broke for you.

http://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html & http://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html imply that these settings do the same thing other than the units used.

**Comment by akrabat** [comment]
Oh, ignore me!
