### ISSUE TITLE
Why do we not send the name of the called action to the predispatch hooks?

### ISSUE THREAD

**Issue by blockjon** [zendframework/zf1#584]
I am referring to this:
https://github.com/zendframework/zf1/blob/master/library/Zend/Controller/Action.php#L500

I'm trying to write a hook does that does something based on the called action.

**Comment by froschdesign** [comment]
> I'm trying to write a hook does that does something based on the called action.

I think, you can use this:
```php
$action = $this->getActionController()->getRequest()->getActionName();
```
(Not tested!)
