### ISSUE TITLE
Zend_Form_Select::getMultiOption($option) does not take option groups into account

### ISSUE THREAD

**Issue by hoppithek** [zendframework/zf1#590]
When setting options with option groups in a Zend_Form_Select it is not possible to retrieve a single option from inside an option group with the getMultiOption function.

```php
<?php
$optionsKey = 'mykey';
$select = new Zend_Form_Select('mySelect');
$select->setMutliOptions(['GROUP 1' => [$optionsKey => 'some value',
                                        /* ... */],
                          /*... */]);

// retrieve all options will include $optionKey
$options = $select->getMultiOptions(); 

// retrieve a single option will return null instead of the option
$option = $select->getMultiOption($optionsKey); 

Zend_Debug::dump($options);
Zend_Debug::dump($option);
```

A similar issue was http://framework.zend.com/issues/browse/ZF-3985 where validation was given the cascading array with option groups, but validation was expecting a flat array without option groups.

**Comment by froschdesign** [comment]
> ```php
// retrieve a single option will return null instead of the option
$option = $select->getMultiOption($optionsKey); 
```

The correct usage is:
```php
$option = $select->getMultiOption('GROUP 1'); 
```

See also in the DocBlock:
```php
/**
 * Retrieve single multi option
 *
 * @param  string $option
 * @return mixed
 */
```
https://github.com/zendframework/zf1/blob/master/library/Zend/Form/Element/Multi.php#L149

**Comment by hoppithek** [comment]
@froschdesign I saw the doc block and is states " Retrieve single multi option" not "Retrieve single top level multi option or option group".

Why would I expect an option group to be a single option, seeing as it is not a selectable option in a HTTP select, nor can it be addressed through the select elements index. 

The correct usage you suggest is exactly the reason why I think this is an issue and unwanted behavior. If this is expected behavior at least the documentation is misleading and option group support is almost non existing in the default `Zend_Form_Element_Select`.

I rather would expect `getMultiOption` to return the option weather it is grouped with others or not. I also would expect addMultiOption to have an optional `$optgroup = null` parameter to later add options and still make use of option groups.

**Comment by froschdesign** [comment]
> …unwanted behavior.

The code "says" something different.

**Comment by hoppithek** [comment]
I am not trying to find out what the code does, the function is short and simple enough to understand at first glance. I am saying it is not doing what it should do, nor what one would expect it to do, not what the doc block says it does. Therefore I think this is an issue.

**Comment by froschdesign** [comment]
> the function is short and simple enough to understand at first glance.

Right, but that is not the question.
We must ask ourselves: can we change the behaviour at this point?

**Comment by hoppithek** [comment]
A change that stays consistent with the current behavior is probably not possible. Nor should it if the current behavior is wrong. Though this is definitive open for discussion. I for one would expect different behavior and consider the current one as wrong.

Anyways the current implementation is also not very consistent with the Zend_Form_Element_Multi superclass as $_options is a public member there it should not be redefined to hold something incompatible in subclasses. It is using the `$_options` array to store grouping as well as options. I suggest to store grouping separately or introduce a GroupedMultiValues class that implements ArrayAccess, so it can be used in place of $_options.

I didn't look to deep into it. Might be both of my first shots at solving this will lead to a dead end.

**Comment by froschdesign** [comment]
Please keep in mind:
> Zend Framework version 1 is currently supported in maintenance mode where bug fixes are accepted until End Of Life is announced. 

http://framework.zend.com/participate/contributor-guide-v1

**Comment by hoppithek** [comment]
Guess I am a few years late ;) I am working around this where I encountered this "issue as I see it". I wont be writing anything for ZF1 nor can I see anyone else doing so, considering the end of life status. Thank you for taking the time. Guess I just need to write my own select element if I really need this changed or even better move to ZF2. Since ZF3 has been announced to come out this year, it definitely is time to move on and leave ZF1 behind.

**Comment by froschdesign** [comment]
> Thank you for taking the time.

You are welcome.

> Since ZF3 has been announced to come out this year, it definitely is time to move on and leave ZF1 behind.

:+1:
