### ISSUE TITLE
Zend_Version incorrect in ZF 1.12.14 

### ISSUE THREAD

**Issue by dotkernel** [zendframework/zf1#592]
now is:
` const VERSION = '1.12.14dev'; `

Must be :

` const VERSION = '1.12.14'; `

**Comment by alcaeus** [comment]
At least it's consistent. From [README.md](https://github.com/zendframework/zf1/blob/release-1.12.14/README.md):
> Zend Framework 1.12.14dev Release. Released on MMM DD, YYYY.

**Comment by weierophinney** [comment]
Fixed with 1.12.15. ;-)
