### ISSUE TITLE
Undefined property $config in Zend_Http_Client_Adapter_Curl

### ISSUE THREAD

**Issue by egeloen** [zendframework/zf1#600]
Hey!

I just upgrade my deps from 1.12.14 to 1.12.15 and it seems there is a break in the curl http adapter. At this [line](https://github.com/zendframework/zf1/blob/master/library/Zend/Http/Client/Adapter/Curl.php#L225) and this [one](https://github.com/zendframework/zf1/blob/master/library/Zend/Http/Client/Adapter/Curl.php#L235), the code relies on `$config` whereas the good one should be `$_config` since the property has been renamed.

**Comment by akrabat** [comment]
Ping @weierophinney…
