### ISSUE TITLE
Undefined property: ::$config in /library/Zend/Http/Client/Adapter/Curl.php 1.12.15

### ISSUE THREAD

**Issue by ingochao** [zendframework/zf1#608]
I think 
 $connectTimeout  = $this->config['timeout']; 
should be
 $connectTimeout  = $this->_config['timeout'];
in 
https://github.com/zendframework/zf1/blob/release-1.12.15/library/Zend/Http/Client/Adapter/Curl.php#L225

and
 $requestTimeout  = $this->config['request_timeout'];
should be
 $requestTimeout  = $this->_config['request_timeout'];
in
https://github.com/zendframework/zf1/blob/release-1.12.15/library/Zend/Http/Client/Adapter/Curl.php#L235

**Comment by froschdesign** [comment]
Already fixed with @cb979e2583b7909fe39c4105cc8cac765331d8e0 (#600)
