### ISSUE TITLE
No translate for displayGroup legend in custom viewScript decorator

### ISSUE THREAD

**Issue by Sohorev** [zendframework/zf1#611]
Version ZF: 1.12.15
I have a form with viewScript decorator. 
My custom decorator has line: 
<?php echo $this->element->getDisplayGroup("conditionals")->getLegend();?>
But this legend not translated
If I change this line to:
<?php echo $this->translate($this->element->getDisplayGroup("conditionals")->getLegend());?>
Then the string is translated.
It seems to me that wrap all legends in translate helper uncomfortable

**Comment by froschdesign** [comment]
The decorator translates the legend, not the element/display group itself.
A translator in all layers of Zend_Form is a very bad idea.

Btw. it is a BC break if we change the behaviour.
