### ISSUE TITLE
Zend_Validate_Hostname does not validate NTP hostnames starting with '0' character

### ISSUE THREAD

**Issue by thaxyh** [zendframework/zf1#612]
Hello, I have a problem with validating NTP hostnames despite using of `ALLOW_ALL` setting. I use PHP 5.6.6 and ZendFramework 1.12.9, but the problem also applies to the latest version of ZF1.

```php
$v = new Zend_Validate_Hostname([ 'allow' => Zend_Validate_Hostname::ALLOW_ALL ]);
var_dump($v->isValid('1.pool.ntp.org')); // bool(true)
var_dump($v->isValid('0.pool.ntp.org')); // bool(false)
```

Usage of `empty()` function (Zend/Validate/Hostname.php:1462 for ZF1.12.15) causes this issue, because `empty(0)` returns `false`.

A simple change might solve it:
```
1462c1462
<                         if (empty($domainPart)) {
---
>                         if (empty($domainPart) && $domainPart != '0') {
```

**Comment by froschdesign** [comment]
@mhujer 
Can you check this?

**Comment by thaxyh** [comment]
Works for me;)

**Comment by thaxyh** [comment]
Any chance to add it to the sources?

**Comment by froschdesign** [comment]
> Any chance to add it to the sources?

…with the [next release](https://github.com/zendframework/zf1/milestones/1.12.16).

**Comment by thaxyh** [comment]
Great! Thank you:)

**Comment by mhujer** [comment]
Created a PR with the fix and test: #615

**Comment by froschdesign** [comment]
@mhujer 
Thanks!

**Comment by glensc** [comment]
why not use `$domainPart !== ''` to match empty string?
