### ISSUE TITLE
Zend_Console_GetOpt fails when supplied a custom argument array if $_SERVER["argv"] is not set

### ISSUE THREAD

**Issue by tasso85** [zendframework/zf1#614]
When creating a new instance of `Zend_Console_GetOpt` supplying a custom `$argv` array, like:

    new Zend_Console_GetOpt($rules, array("--debug"));

It will throw an exception if `$_SERVER["argv"]` is not set, even if it will not be used.

To correct this, I'd say that the check which is on the very first line of `__construct()` should be moved inside the `if (!is_array($argv))` part.

**Comment by froschdesign** [comment]
> It will throw an exception if $_SERVER["argv"] is not set, even if it will not be used.

This is wrong, because `$_SERVER['argv']` is needed:

```php
// Stores the name of the calling application.
$this->_progname = $_SERVER['argv'][0];
```
https://github.com/zendframework/zf1/blob/master/library/Zend/Console/Getopt.php#L257

…and PHP documentation says:
> **Note:** The first argument $argv[0] is always the name that was used to run the script.

http://php.net/manual/en/reserved.variables.argv.php

**Comment by froschdesign** [comment]
Closed due inactivity
