### ISSUE TITLE
Zend_Captcha tries to start session even when setKeepSession(false) is called

### ISSUE THREAD

**Issue by tasso85** [zendframework/zf1#618]
I have just noticed what looks like a bug to me:

In my code, I create a Zend_Captcha_Image, and I set it to not use session:

    $captcha = new Zend_Captcha_Image;
    [...]
    $captcha->setKeepSession(false);
    [...]
    $id = $captcha->generate();
    $word = $captcha->getWord();

However, when calling `generate()` (at which point the session is already started), I get an exception:

    Zend_Session_Exception: session has already been started by session
.auto-start or session_start()

Shouldn't the call to `setKeepSession(false)` prevent this?

**Comment by froschdesign** [comment]
> …and I set it to not use session:

You misunderstand the method `setKeepSession`. Look at the DocBlock:

> Sets if session should be preserved on generate()

https://github.com/zendframework/zf1/blob/master/library/Zend/Captcha/Word.php#L221

Solution: You can give your existing session to the Captcha object with the method `setSession`.

https://github.com/zendframework/zf1/blob/master/library/Zend/Captcha/Word.php#L275

**Comment by tasso85** [comment]
Problem is that our app doesn't use Zend_Session, and session is already started, should I refactor it all to use Zend_Session just so that this component can work?

**Comment by froschdesign** [comment]
> should I refactor it all to use Zend_Session just so that this component can work?

No, you can set your own session class:

https://github.com/zendframework/zf1/blob/master/library/Zend/Captcha/Word.php#L140
https://github.com/zendframework/zf1/blob/master/tests/Zend/Captcha/DumbTest.php#L125
http://framework.zend.com/manual/1.12/en/zend.captcha.adapters.html#zend.captcha.adapters.word
