### ISSUE TITLE
Mark that Zend_Form order has been changed

### ISSUE THREAD

**Issue by KoulSlou** [zendframework/zf1#623]
Under certain conditions I need to change order of the element in a controller code:
```
$form->getElement('element_name')->setOrder(15);
```
After that I expect that function getElementsAndSubFormsOrdered() will return element with a new order. However elements are not re-sorted. If I try to call _sort function from my form it doesn't help because "__orderUpdated" flag is not set to true.

Maybe it's worth to add setOrderUpdated method to the Zend_Form?

**Comment by froschdesign** [comment]
> If I try to call _sort function from my form it doesn't help because "__orderUpdated" flag is not set to true.

If you can call `_sort`, then you can also update the property `_orderUpdated`.

> Maybe it's worth to add setOrderUpdated method to the Zend_Form?

I'm sorry, because:

> For ZF1, we are accepting bug fixes to existing components. Security fixes will be provided on the 1.12 branch until EOL.

http://framework.zend.com/participate/contributor-guide-v1
