### ISSUE TITLE
Zend_Config_Ini handles "foo.bar[]" as section name in section-less INI file

### ISSUE THREAD

**Issue by unarist** [zendframework/zf1#624]
For example, this INI file

```
foo.bar[] = abc
foo.bar[] = def
```

should be parsed same as below YAML:

```yml
foo:
  bar:
    - abc
    - def
```

However, actual result is like this:

```
foo.bar:
  - abc
  - def
```

ZF1 documentation doesn't mention about section-less ini file, but I assumed `Zend_Config_Ini` supports section-less ini file because there is [`Zend_Config_Ini_Test::testZF2508NoSections()`](https://github.com/zendframework/zf1/blob/release-1.12.16/tests/Zend/Config/IniTest.php#L237-L245).

**Comment by froschdesign** [comment]
> actual result is like this

…and this should stay that way! We can not change the current behaviour. (BC break)
