### ISSUE TITLE
Zend_Validate_Hostname allows 127.0.0.0/8 netblock when ALLOW_IP is enabled and ALLOW_LOCAL is disabled

### ISSUE THREAD

**Issue by jcoby** [zendframework/zf1#625]
`Zend_Validate_Hostname` will allow the loopback netblock when created with `Zend_Validate_Hostname::ALLOW_DNS | Zend_Validate_Hostname::ALLOW_IP` is set.

`127.0.0.0/8` is the localhost/loopback netblock according to RFC3330. It would be expected that this netblock is not allowed unless `Zend_Validate_Hostname::ALLOW_LOCAL` is enabled.

**Comment by froschdesign** [comment]
ping @mhujer

**Comment by mhujer** [comment]
I believe this is an expected behaviour. According to the [docs](http://framework.zend.com/manual/1.12/en/zend.validate.set.html#zend.validate.set.hostname) options `ALLOW_IP` and `ALLOW_LOCAL` are independent. `ALLOW_LOCAL` allows local hostnames and does not alter the behaviour of the IP validator.

> The Zend_Validate_Hostname constants are: ALLOW_DNS to allow only DNS hostnames, **ALLOW_IP to allow IP addresses**, **ALLOW_LOCAL to allow local network names**, ALLOW_URI to allow » RFC3986-compliant addresses, and ALLOW_ALL to allow all four above types. *(emphasis mine)*

**Comment by jcoby** [comment]
Fair enough. It just seemed odd that you could easily disallow `localhost` and `something.internal` but no way to reject `127.0.0.1` or `192.168.0.0/16` and other reserved local networks when `ALLOW_IP` is enabled.

It's just a bit of a hidden gotcha when using the validator.

**Comment by mhujer** [comment]
@jcoby Possible workaround is creating a exteded Ip validator based on `Zend_Validate_Ip` and passing it to the Hostname validator using `setIpValidator()` method.

@froschdesign I think we can close this issue.
