### ISSUE TITLE
Speed up Travis tests by removing XDebug

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zf1#631]
Add this to `before_install` section.

`phpenv config-rm xdebug.ini || return 0 ; fi`

**Comment by froschdesign** [comment]
@Maks3w 
If I compare with the [docs](http://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions), is ` || return 0 ; fi` really needed?

**Comment by Maks3w** [comment]
Ignore failures when the file not exists (PHP7, HHVM, ...)

**Comment by froschdesign** [comment]
Thanks!

**Comment by Maks3w** [comment]
@froschdesign The commit is wrong. There are two `before_section` and the last one override the previous

**Comment by froschdesign** [comment]
@Maks3w 
I have already seen it. Thanks,

**Comment by Maks3w** [comment]
Sorry the last `; fi` is not required. On ZF2 we wrap this with a conditional `if`. Soorry

**Comment by froschdesign** [comment]
@Maks3w 
No problem.
