### ISSUE TITLE
List-separator attribute is not being unset for MultiCheckboxes due to a typo.

### ISSUE THREAD

**Issue by IEKing** [zendframework/zf1#637]
Line 249 of `zf1/library/Zend/Form/Decorator/ViewHelper.php` has `'formMulticheckbox'` rather than `'formMultiCheckbox'` which is causing the `'listsep'` attribute to remain set.  This is inconsistent with the other multi elements.

**Comment by froschdesign** [comment]
@IEKing 
Thanks for reporting!
