### ISSUE TITLE
Wrong regex pattern in Zend_Validate_Iban class

### ISSUE THREAD

**Issue by ladjack** [zendframework/zf1#641]
The [Zend_Validate_Iban](https://github.com/zendframework/zf1/blob/master/library/Zend/Validate/Iban.php) has an invalid regex pattern for Macedonia country which looks like this:

`'MK' => '/^MK[0-9]{2}[A-Z]{3}[A-Z0-9]{10}[0-9]{2}$/'`

However according to http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf the bank identifier part must contain only numeric characters (3 digits exactly), rather than letters. So instead that regex pattern should look like:

`'MK' => '/^MK[0-9]{2}[0-9]{3}[A-Z0-9]{10}[0-9]{2}$/'`

That way sample IBAN MK07250120000058984 for Macedonia will pass validation. You can test this sample IBAN on https://www.iban.com for instance.

**Comment by froschdesign** [comment]
@ladjack 
Thanks for reporting!
