### ISSUE TITLE
save method in Zend\Cache\Core accepts only string

### ISSUE THREAD

**Issue by hieuvo** [zendframework/zf1#645]
save method in Zend\Cache\Core accepts only string. It is troublesome when I want to save int type data. I need int type data for later usage of increment method (ex: Memcached, Redis)

**Comment by froschdesign** [comment]
Sorry, but version 1 is in maintenance mode where only bug fixes are accepted. ([see contributor guide](http://framework.zend.com/participate/contributor-guide-v1))

For new features look at ZF3! ([zendframework/zend-cache](https://github.com/zendframework/zend-cache))
