### ISSUE TITLE
Zend_Navigation_Page_Mvc::isActive() doesn't seem to be functioning properly

### ISSUE THREAD

**Issue by acajaja** [zendframework/zf1#646]
A preliminary look at the source shows that $this->_active is not null so the condition if (null === $this->_active) { ... } is never met so the logic to actually figure out if the page is active or not is never run. I commented out the condition and it seems to fix the problem. My active pages were now showing in the navigation.

I output the value of $this->_active before the condition and it was boolean false. I'm couldn't seem to find where this could be set to false since Zend_Navigation_Page_Mvc initializes $this->_active as null, overwriting Zend_Navigation_Page.

I realize this a hack way to do it, but don't have a lot of extra time to dig deeper.

ZF 1.12.16

Thanks for any help!

**Comment by froschdesign** [comment]
> A preliminary look at the source shows that $this->_active is not null so the condition if (null === $this->_active) { ... } is never met so the logic to actually figure out if the page is active or not is never run.

This not true. Please take a look into the [unit test for this class](https://github.com/zendframework/zf1/blob/master/library/Zend/Navigation/Page/Mvc.php).

Please provide an unit test to illustrate your problem.

**Comment by acajaja** [comment]
Ok, thanks. I will do ASAP.

**Comment by froschdesign** [comment]
(I fixed the link.)

Is this still a problem?

**Comment by froschdesign** [comment]
Closing due inactivity.
