### ISSUE TITLE
VERSION constant incorrect for 1.12.17 release tag.

### ISSUE THREAD

**Issue by jonnott** [zendframework/zf1#647]
https://github.com/zendframework/zf1/blob/release-1.12.17/library/Zend/Version.php

..should be 1.12.17, not 1.12.17dev

**Comment by jonnott** [comment]
..also incorrect in README.md

**Comment by froschdesign** [comment]
ping @weierophinney

**Comment by weierophinney** [comment]
We can't fix it in the 1.12.17 release, but noted for the 1.12.18 release.

**Comment by weierophinney** [comment]
1.12.18 release has the correct VERSION constant, and the README file is properly updated.
