### ISSUE TITLE
Cache should implement separate 'add' and 'set' methods

### ISSUE THREAD

**Issue by teo1978** [zendframework/zf1#648]
This seems to be fixed in ZF2, but ZF1 is still maintained, right?

I'm astonished to see that Zend_Cache only has a single method `save` which does not distinguish between what most cache engines call `set` (store a value whether it already exists or not, i.e. create or update it) and `add` (only create it if it doesn't already exists). 

From what I get from this thread (from 5 years ago, and the interface and implementation doesn't seem to have changed since them): http://framework.zend.com/issues/browse/ZF-8856
it looks like the discussion was whether it was better to use `add` or `set` in Memcached for the implementation of `save`, as if `add` and `set` served the same purpose and as if the question was which one is faster, which is simply ridiculous.

**One needs both** `add` and `set` for different purposes. 

When you want to save/update/replace an entry that you don't know (or mind) whether exists or not, you need `set`, while `add` won't do the job because it won't store the new value if one exists.

On the other hand, when you want to create a new variable that is supposed to not already exist (or if you don't need/want to update it if it already exists), you **need** `add`, because it is the only function that does the check and the writing in one **atomic** transaction. If one were to check for existence in application code and then perform a `set`, then there would be a serious performance issue when many **concurrent** scripts simultaneously perform a `set` (even if they all check for existence, because many of them may do the check before any of them has yet created the variable): in this case, all  the `set` actions will **queue up** and all of them will eventually write (usually the same value) one after the other. With `add`, requests will only queue up during the time it takes for **one** of them to perform the writing, then the others will all immediately "fail", hence avoiding a useless series of useless write operations. Which is probably why some people generically claimed that Memcache's set "is slower" and others replied that they had no evidence of that.

Right now, ZendCache in ZF1 only provides a generic `save` method which maps to `set`.

I guess there may be backends which don't have a distinction between set and add (if so, they are useless for any serious scenario where scalability is of any relevance), but in these cases it would be trivial for Zend's backend wrappers to internally use `set` as a fallback for both.

**Comment by froschdesign** [comment]
> …but ZF1 is still maintained, right?

Only maintenance mode where bug fixes are accepted. No new features. ([See contributor guide](http://framework.zend.com/participate/contributor-guide-v1))

**Comment by teo1978** [comment]
I see, but the lack of this feature is a bug (it's a wrong design that renders the cache completely useless)

**Comment by froschdesign** [comment]
> the lack of this feature is a bug (it's a wrong design that renders the cache completely unusable)

That's not the topic! [ZF3 is around the corner](http://framework.zend.com/blog/zend-framework-3-update-and-roadmap.html) and adding new features or a rewrite of old components is a no-go at this point.

Why you do not use the new cache component in your application? It can be the first step for a migration from ZF1 to ZF2/3.
