### ISSUE TITLE
Zend/Soap tests segfault on PHP 5.4

### ISSUE THREAD

**Issue by mhujer** [zendframework/zf1#650]
https://travis-ci.org/zendframework/zf1/jobs/93316220#L1212

```
Finished executing Zend/Session/AllTests.php
Executing Zend/Soap/AllTests.php
PHPUnit 3.7.38 by Sebastian Bergmann.
Configuration read from /home/travis/build/zendframework/zf1/tests/phpunit.xml
........I......................................................  63 / 145 ( 43%)
..I............................................................ 126 / 145 ( 86%)
.................SS
Time: 316 ms, Memory: 8.25Mb
OK, but incomplete or skipped tests!
Tests: 145, Assertions: 274, Incomplete: 2, Skipped: 2.
Segmentation fault (core dumped) <--------
Finished executing Zend/Soap/AllTests.php
Result of Zend/Soap/AllTests.php is 139
```

I think is started unrelated to any change, so I suspect it is related to some changes in travis. They are still running PHP 5.4.37 (latest is 5.4.45).

cc @akrabat

**Comment by mhujer** [comment]
Travis seems to be working on more regular updates https://github.com/travis-ci/travis-ci/issues/4897 so I suggest we can let this wait until they update ten environment? (or maybe we can skip the test for this specific PHP 5.4.37 version to have the build green?)

**Comment by akrabat** [comment]
I do not get a segfault when I test locally on PHP 5.4.46 with PHPUnit 4.8.18.
