### ISSUE TITLE
Expired certificate on packages.zendframework.com

### ISSUE THREAD

**Issue by mhujer** [zendframework/zf1#653]
When I tried to download ZF1 from http://framework.zend.com/downloads/latest#ZF1 (direct URL is https://packages.zendframework.com/releases/ZendFramework-1.12.17/ZendFramework-1.12.17-minimal.tar.gz) I got certificate error, because it expired on 4th December 2015.

cc @weierophinney

**Comment by froschdesign** [comment]
@mhujer 
Is this a problem ZF1 problem or a problem of framework.zend.com or rather zendframework.com?

**Comment by mhujer** [comment]
It was issue with https://packages.zendframework.com/ but it has new certificate now.
