### ISSUE TITLE
zf1-extra is missing in release-1.12.17

### ISSUE THREAD

**Issue by publicitas-deployment** [zendframework/zf1#656]
Hi

I just noticed that the content of zf1-extras is missing from the full release package zip. I did not check the tar.gz. Maybe because zf1-extra has no 1.12.17 release tag?

I copied the zf1-extras from release 1.12.16. That seems to work.

**Comment by froschdesign** [comment]
ping @weierophinney

**Comment by froschdesign** [comment]
Workarounds for version 1.12.17:

- manual Download: https://github.com/zendframework/zf1-extras/releases
- copy the extra library directory from version 1.12.16
- or wait for version 1.12.18

**Comment by weierophinney** [comment]
Can't really fix it in the 1.12.17 release, as that would change the SHA1s, but I'll make sure it's properly tagged and included with 1.12.18.

**Comment by weierophinney** [comment]
1.12.18 release was tagged on zf1-extras, and it will be included in the distribution packages once I've finished building them. (Lack of the 1.12.17 tag on zf1-extras was why it was missing in that version.)
