### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by Sohorev** [zendframework/zf1#662]
I am use a zend framework version 1 and this framework have a class Zend_Session_Namespace with code:

        if (!isset($_SESSION['__ZF'])) {
            return; // no further processing needed
        }

When I run my project with php 7.0.1 this code throw exception: Zend_Session_Exception with message: 
The session has already been started.  The session id must be set first.

I am using two browsers:
in firefox - all ok
in opera I have this bug

On php 5.6 this code work normally

Php bug report here: https://bugs.php.net/bug.php?id=71156&edit=2

**Comment by sshilko** [comment]
u should probably investigate yourself rather than asking for support for such simple browser-specific issue

**Comment by Sohorev** [comment]
What could be the problem with the browser? I immediately surfing at Apache php 5.6 and everything will work. Prompt where to dig. (Какая может быть проблема с браузером? Я тут же переключаю апач на php 5.6 и ве опять работает. Подскажите куда копать)

**Comment by Sohorev** [comment]
I have a simple bootstap for my application:
```
<?php

class Bootstrap extends Zend_Application_Bootstrap_Bootstrap {

    protected function _initLoader() {

        $test1 = new Zend_Session_Namespace("test1");
        $test2 = new Zend_Session_Namespace("test2");
        die("not showed");
    }
}
```

For second time calling $test2 = new Zend_Session_Namespace("test2"); is not working and generate error: 
**The session has already been started.  The session id must be set first.**

I am repeat this error only php7 and opera browser
On php 5.6 or firefox browser my code is working

**Comment by Sohorev** [comment]
Problem was related with parameter session.hash_bits_per_character has other values on the my php 5.6 and my php 7
