### ISSUE TITLE
Zend_Json::encode missing error handling

### ISSUE THREAD

**Issue by tsmgeek** [zendframework/zf1#666]
While decode method has some handling for errors the encode method does not implement any checking of json_last_error() and instead just returns false and the client has to check themselves.
Not sure if this was an oversight or if there is a reason for this that is not known to me.

**Comment by froschdesign** [comment]
@tsmgeek 
You are right, there is no deeper error handling. But at this point we can not change the return result or the current behaviour.

Please make your suggestion for the newer version of [ZF](https://github.com/zendframework/zend-json). Thanks!
