### ISSUE TITLE
Zend_Db_Select - Expression column aren't recognized if doesn't end with parentheses

### ISSUE THREAD

**Issue by sylvainfilteau** [zendframework/zf1#671]
Reading the documentation about [building expression column ](http://framework.zend.com/manual/1.12/en/zend.db.select.html#zend.db.select.building.columns-expr), it says:

> If your column string *contains parentheses*, Zend_Db_Select recognizes it as an expression.

It appears that it's not "strictly" true. Take this select as an example:

```php
$select = $this->_db->select();
$select->from('table1', array('count' => 'COUNT(id) + 1'));
$this->assertEquals("SELECT COUNT(id) + 1 AS \"count\" FROM \"table1\"", $select->assemble());
```

The expression `COUNT(id) + 1` isn't recognized as an expression.

## Context

I maintain a large code base that I recently upgraded from 1.11.19 to 1.12 and it uses Zend_Db_Select extensively. There are many instances where we define an expression that doesn't end with a parentheses and it was recognized as such until now (to be precise, this commit (da09186c60b9168520e994af4253fba9c19c2b3d) is where it stops working as intended). 

I tried to fix the regex to accept my use case but there is many tests that fails after that (mostly related to sql injection protection).

**Comment by froschdesign** [comment]
@ezimuel 
Can you look at this?

**Comment by ezimuel** [comment]
@sylvainfilteau we changed this behavious for a potential SQL injection code. Using regex was not the best solution, I know but we (I) managed in this way.

At this stage, this is more a documentation problem, the correct sentence should be
 > "if your column string is in parentheses, it will be recognized as an expression".

If you change the code using the following example:
```php
$select->from('table1', array('count' => '(COUNT(id) + 1)'));
```
The SQL will syntax render will be:
```sql
SELECT (COUNT(id) + 1) AS `count` FROM `table1`
```
We will fix the documentation, thanks for reporting this!

**Comment by ezimuel** [comment]
@sylvainfilteau maybe this PR https://github.com/zendframework/zf1/pull/492 fixed the issue.

**Comment by sylvainfilteau** [comment]
@ezimuel thanks for your answer. 

Unfortunately for me #492 doesn't fixed the issue. Since then I already changed my app to use explicit Zend_Db_Expr where I had issues. I figured that it would make more sense for ZF team to leave it that way because of the security implication.
