### ISSUE TITLE
Non-existing method getRequired() in Zend_Form-Elements docs

### ISSUE THREAD

**Issue by coreyzev** [zendframework/zf1#679]
Though this seems to state it was fixed in: http://framework.zend.com/issues/browse/ZF-2938

I am still seeing this issue in Zend 1.12.x. In attempting to use `$form->element->getRequired()` I received the error: 

```
Warning: Exception caught by form: Method getRequired does not exist Stack Trace: 
#0 /var/www/html/ch.dev.zerve.com/releases/20160316212611/lib/Zerve/Form/Decorator/BootstrapElement.php(43): Zend_Form_Element->__call('getRequired', Array) 
#1 /var/www/html/ch.dev.zerve.com/releases/20160316212611/lib/Zerve/Form/Decorator/BootstrapElement.php(43): Zend_Form_Element_Text->getRequired() 
...
```

**Comment by froschdesign** [comment]
@coreyzev 
Please use `isRequired`. It is documented in "[Validators - Methods associated with validation include](http://framework.zend.com/manual/1.12/en/zend.form.elements.html#zend.form.elements.validators)".

**Comment by coreyzev** [comment]
Yup, that's what I did. Thanks.

Glad to see the documentation will be fixed to remove or correct `getRequired`.

**Comment by froschdesign** [comment]
@coreyzev 
Thanks for reporting.
