### ISSUE TITLE
Zend_Form_Element_Button::isChecked has wrong documentation

### ISSUE THREAD

**Issue by amballard** [zendframework/zf1#683]
The `isChecked` method for button elements seems to only work in Internet Explorer. Firefox and Chrome do not sent the text of the button as its value the way Internet Explorer does. (Mozilla describes the IE behavior as a bug: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Notes) The value of the button should come from the value attribute, but the value of the element is `NULL` unless explicitly set (which includes loading via `isValid`). Even if the value of the element has been set, the view helper decorator specifically ignores it and returns `NULL` for the element's value for this specific element type, so the value passed to the FormButton view helper is always `NULL`.

As a simple test, I created a controller action containing this basic code:

```PHP
	public function formAction()
	{
	    
	    $form = new Zend_Form();
	    
	    $form
	    ->addElement('submit', 'Submit1')
	    ->addElement('submit', 'Submit2')
	    ->addElement('submit', 'Submit3')
	    ->addElement('button', 'Button1', array('type' => 'submit'))
	    ->addElement('button', 'Button2', array('type' => 'submit'))
	    ->addElement('button', 'Button3', array('type' => 'submit'));

	    
	    
	    $form->setMethod('post');
	    
	    if ($this->_request->isPost()) {
	        
	        Zend_Debug::dump($this->_request->getPost(), 'POST');
	        
	        $form->isValid($this->_request->getPost());
	        
	        Zend_Debug::dump($form->getValues());
	        
	        Zend_Debug::dump($form->Submit1->isChecked(), 'Submit1 is checked');
	        Zend_Debug::dump($form->Submit2->isChecked(), 'Submit2 is checked');
	        Zend_Debug::dump($form->Submit3->isChecked(), 'Submit3 is checked');
	        Zend_Debug::dump($form->Button1->isChecked(), 'Button1 is checked');
	        Zend_Debug::dump($form->Button2->isChecked(), 'Button2 is checked');
	        Zend_Debug::dump($form->Button3->isChecked(), 'Button3 is checked');
	        
	        
    	        	         
	    }
	    $this->view->form = $form;
	    
	}
```

The `isChecked` method works correctly for any of the three submit elements, but does not work for any of the button elements.

**Comment by froschdesign** [comment]
> but does not work for any of the button elements.

This is correct, because no value is explicitly set.

Please compare with the unit tests:

- [`testValidateAlwaysReturnsTrue()`](https://github.com/zendframework/zf1/blob/master/tests/Zend/Form/Element/ButtonTest.php#L144)
- [`testRenderingWithValueAfterValidation()`](https://github.com/zendframework/zf1/blob/master/tests/Zend/Form/Element/ButtonTest.php#L171)

**Comment by amballard** [comment]
It may conform to the unit tests, but the documentation says it should function similiar to Zend_Form_Element_Submit.

http://framework.zend.com/manual/1.12/en/zend.form.standardElements.html#zend.form.standardElements.button

"After populating or validating a form, you can check if the given button was clicked using the `isChecked()` method."

http://framework.zend.com/manual/1.12/en/zend.form.standardElements.html#zend.form.standardElements.submit

"`Zend_Form_Element_Submit` uses the label as the "value" of the submit button, translating it if a translation adapter is present. `isChecked()` checks the submitted value against the label in order to determine if the button was used."

**Comment by froschdesign** [comment]
And how do we create a button element without a `value` attribute?
