### ISSUE TITLE
Optional Zend_Form_Element_File generates fileUploadErrorIniSize error when POSTed

### ISSUE THREAD

**Issue by holtkamp** [zendframework/zf1#685]
I realize Zend Framework 1 is not actively supported anymore, but just wanted to post my experiences here for other ZF1 wanderers out there.

To allow users to upload a file, we use a Zend_Form_Element_File element named "uploadFileX". The uploading itself is done asynchronously using [Cloudinary (which uses JQuery)](http://cloudinary.com/documentation/jquery_image_upload). This means the file is already uploaded (to the cloud) before the form itself is actually submitted. When the form IS submitted, the form element "uploadFileX" is changed to a hidden form field containing the public identifier of the uploaded file, and thereby no actual files are uploaded / POSTed. A 'dummy' input element with id 'file" will be also be POSTed with empty values, this will be ignored when validating however, since it is not part of the original Form Class in PHP.

**Form validation fails**
When validating the form, the following happens
- `Zend_Form_Element_File::isValid()` will perform basic validation, and invoke the isValid() method of the Adapter used to actually upload the file
  - `Zend_File_Transfer_Adapter_Http::isValid()` will detect an empty set of files, while having `$_SERVER['CONTENT_LENGTH'] > 0`, so validation will be triggered, resulting in  error: `array("fileUploadErrorIniSize" => "file 'uploadFileX' has exceeded ini size")`
  - `Zend_File_Transfer_Adapter_Abstract::isValid()` will detect an empty set of files, resulting in  error: `array("fileUploadErrorIniSize" => "file 'uploadFileX' has exceeded ini size")`

So form validation fails, even when the file is marked as 'not-required' using: `$element->setRequired(false);`

This behaviour has been reported previously and seems a combination of:
1. http://stackoverflow.com/questions/17283097/zend-form-failing-validation-with-optional-file-in-ie10
2. http://framework.zend.com/issues/browse/ZF-10279
3. http://framework.zend.com/issues/browse/ZF-12159
4. http://framework.zend.com/issues/browse/ZF-11707
5. http://framework.zend.com/issues/browse/ZF-12189

**Workarounds**
Identified approaches to deal with this:
1. patch: set `$_SERVER['CONTENT_LENGTH'] = 0;` and apply [this patch](http://framework.zend.com/issues/browse/ZF-12189)
2. override: override the `Zend_Form::isValid()` method and filter out the validation error, as suggested [here](http://stackoverflow.com/questions/14736870/zend-form-element-file-and-file-exceeds-the-defined-ini-size-issue/32472069#32472069)
3. prevent: use a dummy FileTransferAdapter which will always return true for the validation, or when the file is marked as optional

The latter seems the most viable / unobtrusive approach. No file needs to be transfered, so no validation has to be performed / validation returns TRUE.

**Example**

``` php
class Zend_File_Transfer_Adapter_HttpDummy extends Zend_File_Transfer_Adapter_Http
{
    public function isValid($files = null) : bool
    {
        if ($this->_options['ignoreNoFile']) {
                return true;
        }

        return parent::isValid($files);
    }
}
```

and, assign the TransferAdapter to the FileElement:

``` php
$element = new Zend_Form_Element_File('uploadFileX');
$element->setTransferAdapter(new Zend_File_Transfer_Adapter_HttpDummy());
```

Would a PR with such a dummy adapter be still accepted to the project?

**UPDATE**
When dealing with the problems of processing the submitted form, another approach was identified: create a new File Element which overrides the specific behavior of `Zend_Form_Element_File`:

``` php
class Zend_Form_Element_File_AsynchronousUpload extends Zend_Form_Element_File
{
    public function __construct($spec, $options = null)
    {
        parent::__construct($spec, $options);
        $this->setRequired(false);
        $this->setValueDisabled(true); //Prevent ZF to attempt to receive the file on calling getValues()
    }

    /**
     * {@inheritdoc}
     */
    public function setValue($value)
    {
        $this->_value = $value;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function isValid($value, $context = null)
    {
        $this->setValue($value);

        return true;
    }
}
```

**Comment by unckleg** [comment]
You must set enctype form attribute to multipart form data.
`$this->setEnctype(Zend_Form::ENCTYPE_MULTIPART);`

You can close this issues.
