### ISSUE TITLE
windows10 can not exec composer update 

### ISSUE THREAD

**Issue by peterpuppy** [zendframework/zf1#694]
here is some console message.
my path is not too long ,and my path don't contain a dot,and the path contain some chinese,it's matter?
my os is window10.i always crazy with this problem

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing dodgepudding/wechat-php-sdk (1.1)
    Downloading: 100%

  [ErrorException]
  ZipArchive::extractTo(D:\php\tpw/vendor/composer/c9cfe002/dodgepudding-wechat-php-sdk
  -3a9b960\wiki/API接口错误码.md): failed to open stream: Invalid argument

**Comment by froschdesign** [comment]
@peterpuppy 
Sorry, but this is not a ZF1 problem! Please look at [dodgepudding/wechat-php-sdk](dodgepudding/wechat-php-sdk).
