### ISSUE TITLE
Ability to list all routes

### ISSUE THREAD

**Issue by madeofsteel** [zendframework/zf1#702]
Is there a zf.sh enhancement or some other built in plugin that will list all the routes on a given zend 1 application?

**Comment by froschdesign** [comment]
You can use `Zend_Controller_Router_Rewrite::getRoutes()`. ([Example](https://github.com/zendframework/zf1/blob/master/tests/Zend/Controller/Router/RewriteTest.php#L106))

**Comment by madeofsteel** [comment]
This is good resource, is there a REPL way of doing this? Or do I have to dump out during the application running (hacky) ?

**Comment by froschdesign** [comment]
> This is good resource, is there a REPL way of doing this?

In most applications the routes are defined in the config files. Read the config files with `Zend_Config` or use plain PHP.

> This is returning blank routes.

Right, because no routes are added to router! ([Another example.](https://github.com/zendframework/zf1/blob/master/tests/Zend/Controller/Router/RewriteTest.php#L334))
