### ISSUE TITLE
variable type hinting with psr-0?

### ISSUE THREAD

**Issue by madeofsteel** [zendframework/zf1#703]
I'm trying to get variable type hinting in the following code (with PHPStorm) but no lock

```php
		/* @var $router \Zend\Controller\Router\Rewrite */
		$router = $front->getRouter();
```

Am I missing something? When type $router-> , there is no autosuggestion to browse through in the class.

**Comment by froschdesign** [comment]
[ZF1 does not use namespaces!](https://github.com/zendframework/zf1/blob/master/library/Zend/Controller/Router/Rewrite.php#L38)

```php
/** @var $router \Zend_Controller_Router_Rewrite */
$router = $front->getRouter();
```
