### ISSUE TITLE
Zend_PDF and IE Edge

### ISSUE THREAD

**Issue by Doublemedia** [zendframework/zf1#708]
Hello Guys,

I am having a weird issue. 

We use ZF 1.12 and creating invoices with Zend_PDF works fine in IE, Firefox and Chrome. But in IE Edge I only see the PDF that I have loaded using Zend_Pdf::load. All the text that we have added to the invoice arent visible.

But when I generated the invoice without the Zend_Pdf::load i do see all the added text in the invoice.

Anyone has the same issue and has an fix for this?

Kind regards,

Erwin

**Comment by froschdesign** [comment]
At the moment, I see no chance to fix the problem. `Zend_Pdf` and [`ZendPdf`](https://github.com/zendframework/ZendPdf) are out of support.

A workaround could be:

- do not display the PDF in the browser
- generate a download

```php
header('Content-type: application/pdf');
header('Content-Disposition: attachment; filename='downloaded.pdf'");
```
