### ISSUE TITLE
You can't disable escaping for radio button labels because of $escape variable is undefined. 

### ISSUE THREAD

**Issue by HenriVesala** [zendframework/zf1#712]
`https://github.com/zendframework/zf1/blob/master/library/Zend/View/Helper/FormRadio.php#L136-L139`

``` 
            // Should the label be escaped?
            if ($escape) {
                $opt_label = $this->view->escape($opt_label);
            }
```

**Comment by froschdesign** [comment]
Please look at the [`Zend_View_Helper_FormElement ::_getInfo()`](https://github.com/zendframework/zf1/blob/master/library/Zend/View/Helper/FormElement.php#L160).
