### ISSUE TITLE
StringParser.php - expression is always true

### ISSUE THREAD

**Issue by AppChecker** [zendframework/zf1#716]
The expression:
```
            if (ord($this->data[$this->offset]) != 0x0A || // Line feed
                ord($this->data[$this->offset]) != 0x0d    // Carriage return
               ) 
```
in [function skipComment](https://github.com/zendframework/zf1/blob/e368bc5a308754852a17d446ec43e0b9202ba7bf/library/Zend/Pdf/StringParser.php#L186) is always true

if  ord($this->data[$this->offset])  is  0x0A -> (ord($this->data[$this->offset]) != 0x0d ) is true -> whole expression is true
if  ord($this->data[$this->offset])  is  0x0d -> (ord($this->data[$this->offset]) != 0x0A ) is true -> whole expression is true
if  ord($this->data[$this->offset])  is  0x0C (some other value) -> (ord($this->data[$this->offset]) != 0x0A ) is true -> whole expression is true

This possible defect found by [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by adamlundrigan** [comment]
We are sorry, but [ZF1 has reached its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html) so only security-related fixes are currently being accepted.
