### ISSUE TITLE
ZF1 EOL and future

### ISSUE THREAD

**Issue by tibor78** [zendframework/zf1#726]
Since ZF1 is EOL and there are many projects still using it i would appreciate if there would still be a way to merge bugfixes and security updates?

perhaps you could release ZF1 as OS or change license to not be your proprietary license?

Would you let someone external handle it? or would you permit branching off a free version of ZF1 to someone external who could handle merges and perhaps link to that?

Why not migrate to ZF2+? They are incomplete so that many missing CORE functions from ZF1 and the overcomplicated MVC / CI requirements make it financially not feasible to migrate certain open source and business applications.

**Comment by froschdesign** [comment]
@tibor78 
**The "Zend Framework" is open source.**
See the license [here on GitHub](https://github.com/zendframework/zf1/blob/master/LICENSE.txt), on the [ZF website](https://framework.zend.com/license) or in [any of the project files](https://github.com/zendframework/zf1/blob/master/library/Zend/Application.php#L5).
