### ISSUE TITLE
Zend_Validate_Hostname add supporting of *.shop TLD

### ISSUE THREAD

**Issue by oleksii-lisovyi** [zendframework/zf1#728]
Hello Guys,

I have an issue related to email validation via Zend_Validate_Hostname for email with TLD .shop.

We use ZF 1.12.16 as Magento 1.9.x lib.
And some customers are not able to register account with email like example@my.shop.

Can you please add TLD .shop as valid one?

Kind regards,

Oleksii Lisovyi

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).

**Comment by oleksii-lisovyi** [comment]
Thx for quick reply! Good luck with developing new version!
