### ISSUE TITLE
Pdo_Pgsql - strings with last slashes could not be found

### ISSUE THREAD

**Issue by noff** [zendframework/zf1#73]
PostgreSQL 9.1.4
PHP 5.3.15
ZendFramework-1.12.1

In PSQL:

	create table links (id serial, url varchar);
	insert into links (url) values ('http://youtube.com/results?search_type=&search_query=\');
	select id from links where url = 'http://youtube.com/results?search_type=&search_query=\'; 
	-> 1

In ZF/PHP:

	$PGSQL = Zend_Db::factory('Pdo_Pgsql', array(...));
	$url = "http://youtube.com/results?search_type=&search_query=\\";
	$select = $PGSQL->select()->from("links")->where("url = ?", $url);
	$link = $PGSQL->fetchRow($select);
	var_dump($link);
	-> false

**Comment by ezimuel** [comment]
I didn't test it using the latest ZF version. I'm closing it because no other reports until 2013.
