### ISSUE TITLE
Version API delivers wrong latest version info

### ISSUE THREAD

**Issue by GitRon** [zendframework/zf1#731]
Hi guys,

your API for showing the latest version of ZF1 (http://framework.zend.com/api/zf-version) is still spitting out "1.12.18" instead of "1.12.20".

I think you are using this inside the "Zend/Version.php" and in addition I use a script for checking this number.

Is there any way you can update the API?

Best regards
Ron

**Comment by froschdesign** [comment]
> Is there any way you can update the API?

Sure. [The problem is the API configuration of the website.](https://github.com/zendframework/zf3-web/issues/31)

Thanks for reporting!

**Comment by GitRon** [comment]
Nice, thanks for fixing it!

**Comment by GitRon** [comment]
It's fixed. Thanks guys!
