### ISSUE TITLE
Zend_Captcha_Word protected function _generateWord()

### ISSUE THREAD

**Issue by Lancer-Serega** [zendframework/zf1#740]
```
if (strlen($word) > $wordLen) {
    $word = substr($word, 0, $wordLen);
}
```

TO

```
if (mb_strlen($word) > $wordLen) {
    $word = mb_substr($word, 0, $wordLen);
}
```

https://toster.ru/q/442395
https://ru.stackoverflow.com/questions/691782/zf1-%D0%9A%D0%B0%D0%BF%D1%87%D0%B0-%D0%BF%D1%80%D0%B8-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D1%85-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2-%D0%B2%D1%8B%D0%B4%D0%B0%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B9-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB-%D0%BA%D0%B0%D0%BA-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81?noredirect=1#comment1022404_691782

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).
