### ISSUE TITLE
Unknown date format, neither date nor time

### ISSUE THREAD

**Issue by agiratech-vignesh** [zendframework/zf1#741]
i am having separate date and time input fields in my form, when i submit the form always getting this error. can any one let me know how to fix this

Exception: 
Fatal error: Uncaught Zend_Locale_Exception: Unknown date format, neither date nor time in '17:41' found in /data/www/library/Zend/library/Zend/Date.php on line 2675

Stacktrace:

#0 /data/www/library/Zend/library/Zend/Date.php(1078): Zend_Date->_calculate('set', '17:41', '17:41', 'en_GB')
#1 /data/www/library/Zend/library/Zend/Date.php(197): Zend_Date->set('17:41', '17:41', 'en_GB')
#2 /data/www/library/COP/Form/Validate/Date.php(68): Zend_Date->__construct('17:41')
#3 /data/www/library/Zend/library/Zend/Form/Element.php(1443): COP_Form_Validate_Date->isValid('17:41', NULL)
#4 /data/www/library/COP/View/Helper/Component/Parser/AbstractParser.php(348): Zend_Form_Element->isValid('17:41')
#5 /data/www/library/COP/View/Helper/Component/Parser/DateTimePicker.php(91): COP_View_Helper_Component_Parser_AbstractParser->_validateFormElement(Object(Zend_Form_Element_Text), Array)
#6 /data/www/library/COP/View/Helper/Component/Forms.php(365): COP_View_Helper_Component_Parser_DateTimePicker->parse(Array, Array, true, Array)
#7 /data/www/library/COP/View/Helper/Component/Parser/FieldContainer.php(61): COP_View_Helper_Component_Forms->_typeSwitch(Array, Array, true)
#8 /data/www/library/COP/View/Helper/Component/Forms.php(321): COP_View_Helper_Component_Parser_FieldContainer->parse(Array, Array, true, NULL)
#9 /data/www/library/COP/View/Helper/Component/Parser/Container.php(74): COP_View_Helper_Component_Forms->_typeSwitch(Array)
#10 /data/www/library/COP/View/Helper/Component/Forms.php(311): COP_View_Helper_Component_Parser_Container->parse(Array, Array, true, Array)
#11 /data/www/library/COP/View/Helper/Component/Forms.php(244): COP_View_Helper_Component_Forms->_typeSwitch(Array, Array)
#12 /data/www/library/COP/View/Helper/Component/Forms.php(75): COP_View_Helper_Component_Forms->_parseOptions(Array)
#13 /data/www/library/COP/View/Helper/Component.php(73): COP_View_Helper_Component_Forms->formsSimple(Array, Object(Shipment_Model_ShipmentFileRow), Array)
#14 /data/www/library/COP/Controller/ShipmentFile/ArrivalManagement/Base.php(2818): COP_View_Helper_Component->forms(Array, Object(Shipment_Model_ShipmentFileRow), Array)
#15 /data/www/library/COP/Controller/ShipmentFile/ArrivalManagement/Base.php(2078): COP_Controller_ShipmentFile_ArrivalManagement_Base->showConsolDeliveryView(Object(Shipment_Model_ShipmentFileRow), Object(Shipment_Model_MasterBillLadingRow), false, Array)
#16 /data/www/library/COP/Controller/ShipmentFile/ArrivalManagement/Base.php(230): COP_Controller_ShipmentFile_ArrivalManagement_Base->showProperDeliveryForm(26, Object(Shipment_Model_ShipmentFileRow), Object(Shipment_Model_MasterBillLadingRow), false, Array)
#17 /data/www/library/Zend/library/Zend/Controller/Action.php(516): COP_Controller_ShipmentFile_ArrivalManagement_Base->deliveryAction()
#18 /data/www/library/Zend/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('deliveryAction')
#19 /data/www/library/Zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#20 /data/www/library/Zend/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#21 /data/www/application/Bootstrap.php(27): Zend_Application_Bootstrap_Bootstrap->run()
#22 /data/www/library/Zend/library/Zend/Application.php(384): Bootstrap->run()
#23 /data/www/public/index.php(48): Zend_Application->run()
#24 {main}

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).
