### ISSUE TITLE
Db\Statement->_parseParameters() bad handling of commented single quote

### ISSUE THREAD

**Issue by lukevi** [zendframework/zf1#742]
/* @var $s \Zend_Db_Statement */
 $s->prepare("/* */ SELECT ':0'"); // fine
 $s->prepare(""/*'*/ SELECT ':0'"); // throws Zend_Db_Statement_Exception, "Invalid bind-variable name ':0'"

Not sure whether this is the job of _stripQuoted or _parseParameters.

**Comment by froschdesign** [comment]
We are sorry, but [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html).
