### ISSUE TITLE
Consider archiving this repo?

### ISSUE THREAD

**Issue by jaydiablo** [zendframework/zf1#746]
https://github.com/blog/2460-archiving-repositories

Might save @froschdesign some time replying to every new issue with the EOL message. :)

**Comment by froschdesign** [comment]
@jaydiablo 
I had the same idea, but:

> We recommend that you close all issues and pull requests…

https://help.github.com/articles/about-archiving-repositories/

**Comment by froschdesign** [comment]
@weierophinney 
Seems to work without closing all issues and PRs. Compare with: https://github.com/thephpleague/json-guard/issues

What do you think? The [forum](https://discourse.zendframework.com/) is still open for questions related to ZF1. (A note in the readme could help.)

**Comment by weierophinney** [comment]
Doing it now...
